using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace ESPresense.Simulation.AccuracyHarness;

public static class AccuracyReport
{
    public const int SchemaVersion = 1;
    public const string HarnessVersion = "0.1.0";

    /// <summary>
    /// Metric rounding precision used both in the serialized report and in
    /// the CI regression guard. Rounding before write means a tolerance
    /// comparison ("is the new value within 5% of the checked-in value?")
    /// is a stable, libm-portable comparison, not a byte-diff. See
    /// docs/accuracy.md for the rationale.
    /// </summary>
    private const int MetricDecimals = 3;

    public static string ToJson(IEnumerable<ScenarioReport> reports)
    {
        var root = new JsonObject
        {
            ["schema_version"] = SchemaVersion,
            ["harness_version"] = HarnessVersion,
            ["scenarios"] = new JsonArray(reports.Select(SerializeScenario).ToArray())
        };
        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            // A report generator must never throw on its own output. The
            // realistic NaN source (0-sample outage drops) is skipped in
            // SerializeScenario like ToMarkdown does; AllowNamedFloatingPointLiterals
            // is a belt-and-suspenders so any residual NaN/Infinity (e.g. a
            // track that never solved) serializes instead of throwing under
            // the default Strict number handling.
            NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals
        };
        return root.ToJsonString(options) + "\n";
    }

    private static JsonNode SerializeScenario(ScenarioReport r)
    {
        var tracks = new JsonArray();
        foreach (var t in r.Tracks)
        {
            var outage = new JsonObject();
            foreach (var kv in t.SingleStationOutage.OrderBy(kv => kv.Key, StringComparer.Ordinal))
            {
                // Match ToMarkdown: a 0-sample drop has NaN metrics (Percentile
                // of an empty list). Skip it rather than emit NaN.
                if (kv.Value.Samples == 0) continue;
                outage[kv.Key] = new JsonObject
                {
                    ["samples"] = kv.Value.Samples,
                    ["median_error_m"] = R(kv.Value.MedianErrorM),
                    ["p95_error_m"] = R(kv.Value.P95ErrorM)
                };
            }

            tracks.Add(new JsonObject
            {
                ["track"] = t.Track,
                ["samples"] = t.Samples,
                ["median_error_m"] = R(t.MedianErrorM),
                ["p95_error_m"] = R(t.P95ErrorM),
                ["mean_error_m"] = R(t.MeanErrorM),
                ["max_error_m"] = R(t.MaxErrorM),
                ["room_misid_rate"] = R(t.RoomMisidRate),
                ["single_station_outage"] = outage
            });
        }

        return new JsonObject
        {
            ["scenario"] = r.Scenario,
            ["locator"] = r.Locator,
            ["base_seed"] = r.BaseSeed,
            ["noise"] = new JsonObject
            {
                ["gaussian_std_db"] = r.Noise.GaussianStdDb,
                ["multipath_probability"] = r.Noise.MultipathProbability,
                ["multipath_attenuation_db"] = r.Noise.MultipathAttenuationDb
            },
            ["tracks"] = tracks
        };
    }

    public static string ToMarkdown(IEnumerable<ScenarioReport> reports)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"<!-- Generated by ESPresense.Companion accuracy harness v{HarnessVersion}; schema v{SchemaVersion} -->");
        sb.AppendLine();
        foreach (var r in reports)
        {
            sb.AppendLine($"### Scenario: `{r.Scenario}` &middot; locator `{r.Locator}`");
            sb.AppendLine();
            sb.AppendLine(
                $"Base seed: `{r.BaseSeed}` &middot; " +
                $"Gaussian σ: `{r.Noise.GaussianStdDb.ToString("F1", CultureInfo.InvariantCulture)} dB` &middot; " +
                $"Multipath p: `{(r.Noise.MultipathProbability * 100).ToString("F0", CultureInfo.InvariantCulture)}%` " +
                $"@ `-{r.Noise.MultipathAttenuationDb.ToString("F0", CultureInfo.InvariantCulture)} dB`");
            sb.AppendLine();
            sb.AppendLine("| Track | n | Median (m) | p95 (m) | Mean (m) | Max (m) | Room mis-id |");
            sb.AppendLine("|---|---:|---:|---:|---:|---:|---:|");
            foreach (var t in r.Tracks)
            {
                sb.AppendLine(
                    $"| `{t.Track}` | {t.Samples} | " +
                    $"{F(t.MedianErrorM)} | {F(t.P95ErrorM)} | {F(t.MeanErrorM)} | {F(t.MaxErrorM)} | " +
                    $"{(t.RoomMisidRate * 100).ToString("F1", CultureInfo.InvariantCulture)}% |");
            }
            sb.AppendLine();
            sb.AppendLine("Single-station-outage (drop each, solve on remaining stations):");
            sb.AppendLine();
            foreach (var t in r.Tracks)
            {
                sb.AppendLine($"- track `{t.Track}`");
                foreach (var kv in t.SingleStationOutage.OrderBy(kv => kv.Key, StringComparer.Ordinal))
                {
                    if (kv.Value.Samples == 0) continue;
                    sb.AppendLine(
                        $"  - drop `{kv.Key}`: median {F(kv.Value.MedianErrorM)}m, " +
                        $"p95 {F(kv.Value.P95ErrorM)}m, n={kv.Value.Samples}");
                }
            }
            sb.AppendLine();
        }
        return sb.ToString();
    }

    private static double R(double v)
    {
        if (double.IsNaN(v) || double.IsInfinity(v)) return v;
        return Math.Round(v, MetricDecimals, MidpointRounding.AwayFromZero);
    }

    private static string F(double v)
    {
        if (double.IsNaN(v)) return "nan";
        return R(v).ToString("F2", CultureInfo.InvariantCulture);
    }
}
